# **TP 3 - IMAGE**

---

Manel Lounissi - Sandeep Nirmal

**Étape 00 — Installer les dépendances**

In [ ]:
!pip install kagglehub[pandas-datasets]
!pip install matplotlib
!pip install numpy


**Étape 1 — Charger un petit dataset d’images.**

In [ ]:
import glob
import os

# Charger toutes les images .png dans /content/
image_files = glob.glob("/content/*.png")

print("Nombre d'images trouvées :", len(image_files))
print("Exemple de chemin :", image_files[0])


Nombre d'images trouvées : 48
Exemple de chemin : /content/audino.png


**Étape 2 — Afficher la dimension d’une image.**

In [ ]:
from PIL import Image

# Charger la première image
img = Image.open(image_files[0])
print("Nom du fichier :", image_files[0])
print("Dimensions de l’image (largeur, hauteur) :", img.size)


Nom du fichier : /content/audino.png
Dimensions de l’image (largeur, hauteur) : (120, 120)


**Étape 3 — Visualiser quelques images avec matplotlib.**

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
for i in range(6):
    img = Image.open(image_files[i])
    plt.subplot(2, 3, i+1)
    plt.imshow(img)
    plt.title(os.path.basename(image_files[i]))
    plt.axis("off")
plt.show()


**Étape 4 — Normaliser les pixels (0–1)**

In [ ]:
import numpy as np

# Convertir une image en tableau numpy et normaliser
img_array = np.array(img) / 255.0
print("Extrait de pixels normalisés (0–1):")
print(img_array[:2, :2, :])


Extrait de pixels normalisés (0–1):
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**Étape 5 — Calculer la moyenne et l’écart-type des pixels d’une image**

In [ ]:
mean = np.mean(img_array)
std = np.std(img_array)

print("Moyenne des pixels :", mean)
print("Écart-type des pixels :", std)


Moyenne des pixels : 0.28207536764705887
Écart-type des pixels : 0.42883867933124525
